@host = http://localhost:5000/restaurants


### get all restaurants
GET {{host}}


### get specific restaurant by id
GET {{host}}/3


### get restaurants by average rating
GET {{host}}/average-rating


### get restaurants by ceratin limit with some start point
GET {{host}}/skip/3/limit/2


### get restaurants by name
GET {{host}}/search/an


### create restaurant
POST {{host}}
Content-Type: application/json

{
  "name": "Maha", 
  "location": "Paandi", 
  "price": "100"
}


### update restaurant
PUT {{host}}
Content-Type: application/json

{
  "id": "3",
  "name": "new data", 
  "price": "3",
  "location": "Salem"
}


### delete restaurant 
DELETE {{host}}/6

