@host = http://localhost:5000/reviews


### get all reviews
GET {{host}}


### get all reviews by restarant id
GET {{host}}/restaurant/2


### create reviews
POST {{host}}
Content-Type: application/json

{
  "restaurant_id": "8",
  "name": "Raj", 
  "body": "Good", 
  "rating": 4
}
